### ISSUE TITLE
Global Vale Package

### ISSUE THREAD

**Issue by nhhagen** [coopnorge/github-workflow-techdocs#16]
## Problem

TechDocs published from different repositories varies in quality. This is caused by the markdown files not being checked against the same [vale](https://vale.sh) configuration.

## Solution

Create 1 Coop [vale package](https://vale.sh/docs/topics/packages/) that we host on GitHub (or a different system). There core package could be made of multiple sub-packages if needed.

> A package is a .zip file that contains a .vale.ini file, a StylesPath folder, or both. You include a package by using the top-level Packages key in your local .vale.ini file.

The vale configuration in [coop-playbook](https://github.com/coopnorge/coop-playbook/.vale.ini) should be used as a base. We should consider to break it up if needed. Some of the content in the vocabulary should perhaps stay local to the Playbook.

The Coop package will make it easier to maintain hight quality documentation across repositories and products.

In a `.vale.ini` file in each consuming repository the Coop package is referenced.

```ini
StylesPath = .github/styles

Packages = https://github.com/coopnorge/vale/releases/download/v1.0.0/Coop.zip

[*.md]
BasedOnStyles = Coop
```

Vale makes it possible to have local configuration in a repository when required.

**Comment by misund** [comment]
I think that ideally the local vale config should be able to see and inherit from the global/shared config.

This would improve local development by allowing a developer to run a vale extension in the editor or ide or cli with a complete setup.

**Comment by nhhagen** [comment]
I should have been more clear, that is what we get by using vale packages.
