### ISSUE TITLE
Ignore vendor folder for linter

### ISSUE THREAD

**Issue by LinMAD** [coopnorge/github-workflow-techdocs#73]
Hi @coopnorge/developer-productivity 

in one of the legacy projects, techdocs workflows start catching the vendor folders for the linting and ofc its breaks.
We cannot delete the vendor folder since it's cupeled with internal integration tests.

Workflow output:
```
**vendor**/github.com/spaolacci/murmur3/README.md
**vendor**/github.com/philhofer/fwd/README.md:6 MD012/no-multiple-blanks Multiple consecutive blank lines [Expected: 1; Actual: 2]
```

Is there a way to configure folders for exclude?

**Comment by nhhagen** [comment]
We are using https://github.com/dorny/paths-filter to drive what files are validated. I'm not sure if this actions has support for excluding files. We still want to validate all markdown files written by us, not only the ones in the `docs/` directory. Here is a snippet of the current implementation:

https://github.com/coopnorge/github-workflow-techdocs/blob/5ed11418d390a9af2a8ddb0d6af16f492627fa12/.github/workflows/techdocs.yaml#L43-L54

A while back we also decided that we should stop vendoring dependencies to avoid these cases. Version locking should be enough.

The easiest fix here is to stop vendoring.
